# -*- coding: utf-8 -*-
"""YolowithoutNumpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTXRhckwsxFR6y7dihjOs0BSdtKrl3YS
"""

# Step 1: Install Ultralytics YOLOv5 (No NumPy Needed)
!pip install ultralytics --quiet

# Step 2: Import and Load YOLOv5
import cv2
from ultralytics import YOLO
from google.colab.patches import cv2_imshow

# Load pretrained YOLOv5 model
model = YOLO('yolov5s.pt')  # You can change to yolov8n.pt or other versions

# Step 3: Run Inference on Sample Image
# This works without requiring NumPy
results = model('https://ultralytics.com/images/bus.jpg')

# Step 4: Show Results
results[0].show()  # Display bounding boxes

# Step 4: Upload an Image
from google.colab import files
uploaded = files.upload()

# Step 5: Perform Detection
import io
import cv2
from google.colab.patches import cv2_imshow

for fname in uploaded.keys():
    image_path = fname
    # Read image using OpenCV (no NumPy)
    image = cv2.imread(image_path)

    # Run YOLO model
    results = model(image)

    # Annotate image with results
    annotated_image = results[0].plot()

    # Display the result
    print(f"Detected objects in {fname}:")
    print(results[0].verbose())
    cv2_imshow(annotated_image)

# Display the result
  print(f"Detected objects in {fname}:")
  results[0].print()
  cv2_imshow(annotated_image)